### ISSUE TITLE
Flutter 3.10.0 support

### ISSUE THREAD

**Issue by mnespor** [urbanairship/airship-flutter#170]
# Preliminary Info

### What Airship dependencies are you using?
airship_flutter: ^6.3.1

### What are the versions of any relevant development tools you are using?

Flutter 3.10.0
Dart 3.0.0
DevTools 2.23.1

# Report

### What unexpected behavior are you seeing?
I see the following error during `flutter pub get`:
```
Because airship_flutter >=4.3.0 depends on intl >=0.15.7 <0.18.0 and every version of flutter_localizations from sdk depends on intl 0.18.0, airship_flutter >=4.3.0 is incompatible with
  flutter_localizations from sdk.
```
pubspec.yaml snippet:
```
  airship_flutter: ^6.3.1
  flutter_localizations: # gives us support for plurals
    sdk: flutter
```

### What is the expected behavior?
`flutter pub get` succeeds, as it does with this change: https://github.com/urbanairship/airship-flutter/compare/main...mnespor:airship-flutter:main
pubspec.yaml:
```
  airship_flutter:
    git:
      url: https://github.com/mnespor/airship-flutter.git
      ref: main
  flutter_localizations: # gives us support for plurals
    sdk: flutter
```

### What are the steps to reproduce the unexpected behavior?
1. Use the latest version of airship_flutter alongside the latest version of flutter_localizations.
2. Execute `flutter pub get`

### Do you have logging for the issue?
No logs available
